export enum StoreKey {
	ActiveTags = 'kurosearch:active-tags',
	ActiveSupertags = 'kurosearch:active-supertags',
	BlockedContent = 'kurosearch:blocked-content',
	LocalstorageEnabled = 'kurosearch:localstorage-enabled',
	ResultColumns = 'kurosearch:result-columns',
	Supertags = 'kurosearch:supertags',
	Filter = 'kurosearch:filter',
	Sort = 'kurosearch:sort',
	Results = 'kurosearch:results',
	Theme = 'kurosearch:theme',
	AlwaysLoop = 'kurosearch:always-loop',
	CookiesAccepted = 'kurosearch:cookies-accepted',
	HighResolutionEnabled = 'kurosearch:high-resolution-enabled',
	HighResolutionMultiColEnabled = 'kurosearch:high-resolution-multi-col-enabled',
	WideLayoutEnabled = 'kurosearch:wide-layout-enabled',
	FullscreenHintDone = 'kurosearch:fullscreen-hint-done',
	AutoplayFullscreenEnabled = 'kurosearch:autoplay-fullscreen-enabled-done',
	AutoplayFullscreenDelay = 'kurosearch:autoplay-fullscreen-delay',
	TagsShortcut = 'kurosearch:tags-shortcut'
}
